### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by fkemps** [jonathanendersby/loonlogs#1]
Hi Jonathan,

I stumbled across your code and tried to get it installed, but failed unfortunately.
Can you add short installation guidance on the README?

On lightttp I added a section shown below to point towards your code next to radiosonde_auto_rx directory.

```
url.redirect += (
  "^/loonlogs/$" => "/loonlogs/list.html",
  "^/loonlogs$" => "/loonlogs/list.html"
)

alias.url += (
  "/loonlogs/" => "/home/user/loonlogs/"
)
```

The listing page is presented but the actual "log search" logic not applied.

Thanks in advance,
Ferry

**Comment by jonathanendersby** [comment]
@fkemps  woah, no idea how you stumbled across this. I was literally only using github to move code to my pi for testing in 'production'.

The codebase has changed a lot since you last played with it. I suggest you give it another try and see if you can get it up and running based on the new readme.

**Comment by jonathanendersby** [comment]
I'm going to close this issue as the codebase is totally different to what it was when you created your issue.
